// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjwcoyoczfxesduraoqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqd2NveW9jemZ4ZXNkdXJhb3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQ5MjIsImV4cCI6MjA2NjI4MDkyMn0.Dg8p5_CCazCBZqXuZ653gtXKD8D1udQDSrVQwL8vcMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);